### ISSUE TITLE
Improving the design of footer

### ISSUE THREAD

**Issue by isyneha** [DecodersCommunity/portfolio-builder#34]
![image](https://user-images.githubusercontent.com/79058289/194747802-edd8dc37-b609-44b3-a0b3-1bd03c3d0c47.png)
As can be seen that height of the footer is too much. So, if anyone can help with the redesigning of the footer are welcome.

**Comment by sid172014** [comment]
Hey there ! i can help with this .... can you please assign this to me and share more info about the specifics you want to have in that footer ,, like social media icons , contact info , brand logo ..

**Comment by isyneha** [comment]
Ya sure, I'm assigning it to you. Go ahead. You can put social media icons that are just above the green line in the footer itself. Also, reduce its height. That's all from my side. If you have any other designs in mind, you can implement them as well. But just make sure to make it responsive.

**Comment by sid172014** [comment]
Aight , Thanks

**Comment by sid172014** [comment]
Hey, i've designed the footer section and created a pull request , please have a look and let me know if there's any changes you want or anything to add or detract

**Comment by sid172014** [comment]
My PR no is #39

**Comment by isyneha** [comment]
@sid172014, you have done a good job! Will let you know about it in a while.

**Comment by sid172014** [comment]
Okay @isyneha Do let me know if there's anything else i can dig my head in lol , Thank you !

**Comment by isyneha** [comment]
If you want you can work for overall design of the current page.

**Comment by sid172014** [comment]
Sure! , would love to do that once this footer request is merged ..

**Comment by isyneha** [comment]
Completed as in Pull Request #42
