### ISSUE TITLE
Improvement in the Readme File

### ISSUE THREAD

**Issue by isyneha** [DecodersCommunity/portfolio-builder#5]
As the name suggests in this issue you can improve the documentation of the Readme File. Improvise it with illustrations and examples. The documentation can have an illustrative description of how you can contribute to the portfolio-builder repository. Any other innovative idea is always welcome. Happy coding & contributing!

**Comment by chakrinya009** [comment]
@isyneha can you please assign this issue to me

**Comment by isyneha** [comment]
Sure, I can. Here you go.

**Comment by Ujjawal0204** [comment]
Hey, is it still open. Can I work on it

**Comment by isyneha** [comment]
@chakrinya009 Would you take more time?

**Comment by chakrinya009** [comment]
In my area power off mam for road extension due to this i am unable to fix
this issue. Sorry mam

**Comment by isyneha** [comment]
It is okay!

**Comment by isyneha** [comment]
@Ujjawal0204 assigning it to you.

**Comment by Ujjawal0204** [comment]
> 

thanku

**Comment by isyneha** [comment]
Closed as completed as per #41
