### ISSUE TITLE
Improvement in the Base template

### ISSUE THREAD

**Issue by isyneha** [DecodersCommunity/portfolio-builder#6]
Are you a front-end developer who likes to create designs through codes? Then, here it is. Use your JavaScript and CSS skills to improvise the design of base template. You can make this responsive or add some JavaScript to make it more functional. Creativity is all yours. So, get your skills at work.

**Comment by Anish-Parkhi** [comment]
Hello I am ready to work on this issue

**Comment by isyneha** [comment]
Yeah sure. I am assigning it to you.

**Comment by SharmilaChoudhary** [comment]
hey @isyneha  I want to work on this issue

**Comment by isyneha** [comment]
Sure, assigning it to you.
